name: Events Demo 1
on:
  pull_request:
    types: 
      - opened
    branches:
      - main
      ##we are able to use a "regular" expression stale
      - 'dev-*'
   ##or
## [opened, edited]
  workflow_dispatch:
  push:
    branches:
      - main
      ##we are able to use a "regular" expression stale
      - 'dev-*'
    paths:
    ##we can run workflows if any file changes on specific paths
      - '**.js'
    paths-igonore:
     ## it  means that if any file here changes workflow will not run
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."

## by feault fork dont tirgger a pull requuest based workflow
## so they first need aprove via cli
## we can skip the actions using special commands into our commit
##ig commit -m "my message [skip ci]"