##creating a composy custom action
name: "Get dependies"
##this actions is not a workflow, so not containt on:
description: 'Fet the dependencies (via npm)  and cache the  and cache them.'
##for accept imput we only use the input reserved parameter
inputs:
  ##this names are up to us
  caching: 
    ##this attribute is obligatores
    description: 'Wheteher to cache depencies or not.'
    ##we can make it required or not
    required: true
    ##we can also add default values
    default: 'true'
outputs:
  used-cache:
    description: "Whether the cache was used."
    ##steps githubactions object refering to any step id
    value: ${{ steps.install.outputs.cache }}
runs:
  ##this is obligatiry
  using: 'composite'
  ##now we define the steps as on a workflow
  steps:
    - name: Cache dependencies
      ##nputs is another github actions object
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
      ## we create the github output for this specific step
        echo "cache='${{ inputs.caching }}" >> $GITHUB_OUTPUT
      #on custom actions we must specify the shell
      shell: bash