name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        ##by default we have acces to some metadata into workflow
        run: echo "${{ toJSON(github) }}"
        ##this is the way to acces reserved keys
        ##ther are commonly called context objects